import { useEffect } from 'react'
const roles = [
  { name: ['Branch Admin', 'Admin Cawangan'], title: ['A clearer view of your kindergarten.', 'Gambaran tadika yang lebih jelas.'], body: ['Keep student records, teachers and classes organised. Follow attendance and school fees within your own branch, with the right access for each member of your team.', 'Susun rekod murid, guru dan kelas. Pantau kehadiran dan yuran dalam cawangan sendiri, dengan akses yang sesuai untuk setiap ahli pasukan.'], tags: [['Student registration', 'Class management', 'Branch oversight'], ['Pendaftaran murid', 'Pengurusan kelas', 'Pemantauan cawangan']] },
  { name: ['Teacher', 'Guru'], title: ['More time for little learners.', 'Lebih masa untuk anak didik.'], body: ['Bring your teaching day together: assigned classes, attendance and homework. Keep learning activities organised and share updates with families through announcements.', 'Satukan urusan mengajar: kelas yang ditugaskan, kehadiran dan kerja rumah. Susun aktiviti pembelajaran dan kongsi maklumat dengan keluarga melalui pengumuman.'], tags: [['Classes', 'Attendance', 'Homework'], ['Kelas', 'Kehadiran', 'Kerja rumah']] },
  { name: ['Finance', 'Kewangan'], title: ['Keep school fees in focus.', 'Urus yuran dengan lebih teratur.'], body: ['Review invoices, follow up outstanding fees and verify bank-transfer proof against actual bank transactions. Keep payment records easy to find for your branch.', 'Semak invois, susuli yuran tertunggak dan sahkan bukti pindahan dengan transaksi bank sebenar. Simpan rekod bayaran cawangan supaya mudah dirujuk.'], tags: [['Invoices', 'Payment verification', 'Payment records'], ['Invois', 'Pengesahan bayaran', 'Rekod bayaran']] },
  { name: ['Parents', 'Ibu Bapa'], title: ['Stay close to your child’s day.', 'Ikuti hari anak anda.'], body: ['Find your child’s attendance, homework and school announcements in one place. Review school invoices and submit transfer proof. Siblings can share one linked parent account.', 'Lihat kehadiran, kerja rumah dan pengumuman sekolah anak dalam satu tempat. Semak invois dan hantar bukti pindahan. Adik-beradik boleh dipautkan kepada satu akaun ibu bapa.'], tags: [['Child updates', 'School announcements', 'School fees'], ['Maklumat anak', 'Pengumuman sekolah', 'Yuran sekolah']] },
  { name: ['Students', 'Murid'], title: ['At the heart of every school day.', 'Di tengah setiap usaha kita.'], body: ['Each student has an organised record connecting their class, attendance and family. Teachers and parents manage these details on their behalf—young children do not need their own login.', 'Setiap murid mempunyai rekod yang menghubungkan kelas, kehadiran dan keluarga. Guru dan ibu bapa mengurus maklumat ini bagi pihak mereka—kanak-kanak tidak memerlukan akaun log masuk sendiri.'], tags: [['Student records', 'Class enrolment', 'Family links'], ['Rekod murid', 'Pendaftaran kelas', 'Pautan keluarga']] },
]
const faqs = [
  [['Who is this platform for?', 'Untuk siapa platform ini?'], ['Kindergartens that want to organise daily operations for branch admins, teachers, finance staff and parents. Student information is managed by adults; students do not need to log in.', 'Untuk tadika yang mahu menyusun operasi harian admin cawangan, guru, staf kewangan dan ibu bapa. Maklumat murid diurus oleh orang dewasa; murid tidak perlu log masuk.']],
  [['What does one plan cover?', 'Apakah yang disertakan dalam satu pelan?'], ['One kindergarten branch and one branch admin. Basic includes up to 3 teachers, Standard 5 and Premium 10. Student capacity depends on the selected plan.', 'Satu cawangan tadika dan satu admin cawangan. Basic merangkumi sehingga 3 guru, Standard 5 dan Premium 10. Kapasiti murid bergantung pada pelan yang dipilih.']],
  [['Do siblings need separate parent accounts?', 'Adakah adik-beradik memerlukan akaun ibu bapa berasingan?'], ['No. Siblings can be linked to the same parent account, so parents can follow their children from one login.', 'Tidak. Adik-beradik boleh dipautkan kepada akaun ibu bapa yang sama supaya ibu bapa boleh mengikuti anak-anak melalui satu log masuk.']],
  [['Can parents pay online?', 'Bolehkah ibu bapa membayar secara online?'], ['Parents can submit proof after a manual bank transfer for verification. Online checkout is not active yet while the payment provider setup is being completed.', 'Ibu bapa boleh menghantar bukti selepas pindahan bank manual untuk pengesahan. Checkout online belum aktif sementara persediaan penyedia bayaran dilengkapkan.']],
  [['Does Join Us activate an account immediately?', 'Adakah Join Us terus mengaktifkan akaun?'], ['Not yet. The current registration page lets you select a plan, enter details and review them. It does not submit your registration, create an account or charge you.', 'Belum. Halaman pendaftaran sekarang membolehkan anda memilih pelan, mengisi maklumat dan menyemaknya. Ia belum menghantar pendaftaran, mencipta akaun atau mengenakan bayaran.']],
  [['Can everyone see every branch?', 'Bolehkah semua orang melihat setiap cawangan?'], ['Access follows each user’s role and branch assignment. Branch admins work within their own branch; superadmins oversee the system across branches.', 'Akses mengikut peranan dan penugasan cawangan pengguna. Admin cawangan mengurus cawangan sendiri; superadmin memantau sistem merentas cawangan.']],
]

export function RoleSections({ language, compact = false }) {
  const i = language === 'en' ? 0 : 1
  return <section className="role-section"><div className="section-heading"><p className="eyebrow">{i === 0 ? 'ONE COMMUNITY. DIFFERENT ROLES.' : 'SATU KOMUNITI. PELBAGAI PERANAN.'}</p><h2>{i === 0 ? 'A place for everyone.' : 'Ruang untuk semua.'}</h2></div><div className={compact ? 'role-grid' : 'role-stories'}>{roles.map((role, index) => <article className="role-story" id={`role-${["admin", "teacher", "finance", "parents", "students"][index]}`} key={index}><div className="role-number">0{index + 1}</div><div><p className="role-label">{role.name[i]}</p><h3>{role.title[i]}</h3><p>{role.body[i]}</p>{!compact && <ul className="role-tags">{role.tags[i].map(tag => <li key={tag}>{tag}</li>)}</ul>}</div></article>)}</div>{compact && <a className="secondary" href="#/what-we-do">{i === 0 ? 'Explore what we do →' : 'Lihat apa yang kami lakukan →'}</a>}</section>
}

export function InfoPage({ language, page, roleId, onJoin }) {
  useEffect(() => {
    if (roleId) document.getElementById(`role-${roleId}`)?.scrollIntoView({ block: 'start' })
  }, [roleId])
  const en = language === 'en'
  return <><section className="info-hero"><p className="eyebrow">{page === 'faq' ? (en ? 'FAQs' : 'SOALAN LAZIM') : (en ? 'WHAT WE DO' : 'APA YANG KAMI LAKUKAN')}</p><h1>{page === 'faq' ? (en ? 'Good questions. Clear answers.' : 'Soalan anda. Jawapan yang jelas.') : (en ? 'Better school days. Together.' : 'Hari persekolahan lebih baik. Bersama.')}</h1><p className="intro">{page === 'faq' ? (en ? 'A little clarity before your next step.' : 'Sedikit penjelasan sebelum langkah seterusnya.') : (en ? 'We bring the people and daily tasks of your kindergarten into one connected workspace.' : 'Kami satukan warga dan tugasan harian tadika dalam satu ruang kerja yang saling terhubung.')}</p></section>{page === 'faq' ? <section className="faq-list" aria-label={en ? 'Frequently asked questions' : 'Soalan lazim'}>{faqs.map(([question, answer], index) => <details key={index}><summary>{question[en ? 0 : 1]}<span aria-hidden="true">+</span></summary><p>{answer[en ? 0 : 1]}</p></details>)}</section> : <RoleSections language={language} />}<section className="closing"><div><p className="eyebrow">{en ? 'LET’S GET STARTED' : 'JOM BERMULA'}</p><h2>{en ? 'Make room for a better school day.' : 'Mulakan hari persekolahan yang lebih teratur.'}</h2></div><button className="button" onClick={() => onJoin()}>{en ? 'Join Us →' : 'Daftar →'}</button></section></>
}
