// Isolated PostgreSQL test: node supabase/tests/parent_payments.mjs /path/to/@electric-sql/pglite/dist/index.js
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'
const { PGlite } = await import(pathToFileURL(process.argv[2]).href)
const db = new PGlite()
const superId = '10000000-0000-0000-0000-000000000001'
const adminId = '10000000-0000-0000-0000-000000000002'
await db.exec(`
CREATE ROLE anon; CREATE ROLE authenticated;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS UUID LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('test.user_id', true), '')::UUID $$;
CREATE TABLE public.branches(id UUID PRIMARY KEY, name TEXT);
CREATE TABLE public.users(id UUID PRIMARY KEY, full_name TEXT, role_id SMALLINT, branch_id UUID);
CREATE FUNCTION public.auth_user_role() RETURNS SMALLINT LANGUAGE sql SECURITY DEFINER STABLE AS $$ SELECT role_id FROM public.users WHERE id = auth.uid() $$;
CREATE FUNCTION public.auth_user_branch() RETURNS UUID LANGUAGE sql SECURITY DEFINER STABLE AS $$ SELECT branch_id FROM public.users WHERE id = auth.uid() $$;
INSERT INTO users VALUES ('${superId}', 'Superadmin', 1, NULL), ('${adminId}', 'Admin', 2, NULL);
`)
for (const name of ['students', 'branch_staff', 'classes', 'parents', 'attendances', 'payments', 'expenses', 'assignments', 'assignment_submissions', 'student_classes', 'announcements', 'subscription_plans', 'subscription_invoices']) {
  await db.exec(`CREATE TABLE public.${name}(id INTEGER PRIMARY KEY, branch_id UUID);`)
}
await db.exec(await readFile(new URL('../migrations/013_audit_logs.sql', import.meta.url), 'utf8'))

const parentId='10000000-0000-0000-0000-000000000004'
const financeId='10000000-0000-0000-0000-000000000005'
const otherId='10000000-0000-0000-0000-000000000006'
const branchA='20000000-0000-0000-0000-000000000001'
const branchB='20000000-0000-0000-0000-000000000002'
await db.exec(`
ALTER TABLE students ADD name TEXT, ADD full_name TEXT;
ALTER TABLE payments ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE payments ADD student_id INTEGER, ADD invoice_no TEXT, ADD payment_type TEXT, ADD amount NUMERIC,
 ADD due_date DATE, ADD status TEXT, ADD payment_date DATE, ADD payment_method TEXT, ADD verified_by UUID, ADD verified_at TIMESTAMPTZ;
ALTER TABLE parents ADD user_id UUID;
CREATE TABLE student_parents(student_id INTEGER,parent_id INTEGER);
ALTER TABLE users ADD status TEXT DEFAULT 'active';
CREATE TABLE notifications(id SERIAL PRIMARY KEY,user_id UUID,title TEXT,message TEXT,is_read BOOLEAN,notification_type TEXT);
CREATE SCHEMA storage;
CREATE TABLE storage.buckets(id TEXT PRIMARY KEY,name TEXT,public BOOLEAN,file_size_limit BIGINT,allowed_mime_types TEXT[]);
CREATE TABLE storage.objects(id UUID DEFAULT gen_random_uuid(),bucket_id TEXT,name TEXT);
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
GRANT USAGE ON SCHEMA storage TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON storage.objects TO authenticated;
INSERT INTO branches VALUES ('${branchA}','A'),('${branchB}','B');
UPDATE users SET branch_id='${branchA}' WHERE id='${adminId}';
INSERT INTO users(id,full_name,role_id,branch_id) VALUES ('${parentId}','Parent',4,NULL),('${financeId}','Finance',5,'${branchA}'),('${otherId}','Other admin',2,'${branchB}');
INSERT INTO students(id,branch_id,name,full_name) VALUES (1,'${branchA}','Child A','Child A'),(2,'${branchB}','Child B','Child B');
INSERT INTO parents(id,user_id) VALUES(1,'${parentId}');
INSERT INTO student_parents VALUES(1,1);
`)
const migration=await readFile(new URL('../migrations/015_parent_payments.sql',import.meta.url),'utf8')
await db.exec(migration)
await db.exec(migration)
await db.exec(`ALTER TABLE payments ENABLE ROW LEVEL SECURITY; CREATE POLICY read_fee ON payments FOR SELECT TO authenticated USING(public.can_read_fee(id));`)
async function as(id){await db.exec(`SET ROLE authenticated; SET test.user_id = '${id}';`)}
await db.exec(await readFile(new URL('../migrations/021_hq_payment_account.sql',import.meta.url),'utf8'))
const controls=await readFile(new URL('../migrations/022_finance_controls.sql',import.meta.url),'utf8')
await db.exec(controls);await db.exec(controls)
await as(superId)
await db.query("SELECT save_hq_payment_account('HQ Bank','HQ','12345678',0)")
await as(adminId)
const invoice=(await db.query("SELECT * FROM create_fee_invoice(1,'Test',100,CURRENT_DATE-35)")).rows[0]
const second=(await db.query("SELECT * FROM create_fee_invoice(1,'Wrong',200,CURRENT_DATE-10)")).rows[0]
await as(parentId)
const path=`${parentId}/${invoice.id}/proof.pdf`
await db.query("INSERT INTO storage.objects(bucket_id,name) VALUES('payment-proofs',$1)",[path])
const proof=(await db.query('SELECT * FROM submit_payment_proof($1,$2,$3)',[invoice.id,path,'HQ-123'])).rows[0]
await assert.rejects(db.query('SELECT fee_aging_report()'),/Finance access/)
await as(financeId)
await assert.rejects(db.query("SELECT void_fee_invoice($1,'Wrong')",[second.id]),/Only an administrator/)
await as(otherId)
assert.equal((await db.query('SELECT fee_aging_report() AS r')).rows[0].r.total,0)
await assert.rejects(db.query("SELECT void_fee_invoice($1,'Wrong')",[second.id]),/unavailable/)
await as(adminId)
let report=(await db.query('SELECT fee_aging_report() AS r')).rows[0].r
assert.equal(report.total,2)
assert.equal(report.buckets.find(b=>b.bucket==='31–60 days').amount,100)
assert.equal(report.rows.find(r=>r.id===invoice.id).awaiting_verification,true)
await assert.rejects(db.query("SELECT void_fee_invoice($1,'Wrong')",[invoice.id]),/without pending/)
await assert.rejects(db.query("SELECT void_fee_invoice($1,' ')",[second.id]),/Enter a reason/)
await db.query("SELECT void_fee_invoice($1,'Duplicate invoice')",[second.id])
await db.query("SELECT void_fee_invoice($1,'Duplicate invoice')",[second.id])
assert.equal((await db.query('SELECT status FROM payments WHERE id=$1',[second.id])).rows[0].status,'void')
assert.equal((await db.query('SELECT fee_aging_report() AS r')).rows[0].r.total,1)
await db.query('SELECT review_payment_proof($1,true)',[proof.id])
await assert.rejects(db.query("SELECT void_fee_invoice($1,'Wrong')",[invoice.id]),/Only unpaid/)
assert.equal((await db.query('SELECT fee_aging_report() AS r')).rows[0].r.total,0)
await db.exec('RESET ROLE;')
assert.equal((await db.query("SELECT * FROM notifications WHERE title='School fee invoice cancelled'")).rows.length,1)
assert.ok((await db.query("SELECT * FROM audit_logs WHERE module='payments' AND 'void_reason'=ANY(changed_fields)")).rows.length>0)
await db.close()
console.log('PASS: HQ proof without branch account, aging, role/branch isolation, proof/paid void protection, reasons, audit and idempotent notifications.')
