// Isolated PostgreSQL test: node supabase/tests/parent_payments.mjs /path/to/@electric-sql/pglite/dist/index.js
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'
const { PGlite } = await import(pathToFileURL(process.argv[2]).href)
const db = new PGlite()
const superId = '10000000-0000-0000-0000-000000000001'
const adminId = '10000000-0000-0000-0000-000000000002'
await db.exec(`
CREATE ROLE anon; CREATE ROLE authenticated;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS UUID LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('test.user_id', true), '')::UUID $$;
CREATE TABLE public.branches(id UUID PRIMARY KEY, name TEXT);
CREATE TABLE public.users(id UUID PRIMARY KEY, full_name TEXT, role_id SMALLINT, branch_id UUID);
CREATE FUNCTION public.auth_user_role() RETURNS SMALLINT LANGUAGE sql SECURITY DEFINER STABLE AS $$ SELECT role_id FROM public.users WHERE id = auth.uid() $$;
CREATE FUNCTION public.auth_user_branch() RETURNS UUID LANGUAGE sql SECURITY DEFINER STABLE AS $$ SELECT branch_id FROM public.users WHERE id = auth.uid() $$;
INSERT INTO users VALUES ('${superId}', 'Superadmin', 1, NULL), ('${adminId}', 'Admin', 2, NULL);
`)
for (const name of ['students', 'branch_staff', 'classes', 'parents', 'attendances', 'payments', 'expenses', 'assignments', 'assignment_submissions', 'student_classes', 'announcements', 'subscription_plans', 'subscription_invoices']) {
  await db.exec(`CREATE TABLE public.${name}(id INTEGER PRIMARY KEY, branch_id UUID);`)
}
await db.exec(await readFile(new URL('../migrations/013_audit_logs.sql', import.meta.url), 'utf8'))

const parentId='10000000-0000-0000-0000-000000000004'
const financeId='10000000-0000-0000-0000-000000000005'
const otherId='10000000-0000-0000-0000-000000000006'
const branchA='20000000-0000-0000-0000-000000000001'
const branchB='20000000-0000-0000-0000-000000000002'
await db.exec(`
ALTER TABLE students ADD name TEXT, ADD full_name TEXT;
ALTER TABLE payments ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE payments ADD student_id INTEGER, ADD invoice_no TEXT, ADD payment_type TEXT, ADD amount NUMERIC,
 ADD due_date DATE, ADD status TEXT, ADD payment_date DATE, ADD payment_method TEXT, ADD verified_by UUID, ADD verified_at TIMESTAMPTZ;
ALTER TABLE parents ADD user_id UUID;
CREATE TABLE student_parents(student_id INTEGER,parent_id INTEGER);
ALTER TABLE users ADD status TEXT DEFAULT 'active';
CREATE TABLE notifications(id SERIAL PRIMARY KEY,user_id UUID,title TEXT,message TEXT,is_read BOOLEAN,notification_type TEXT);
CREATE SCHEMA storage;
CREATE TABLE storage.buckets(id TEXT PRIMARY KEY,name TEXT,public BOOLEAN,file_size_limit BIGINT,allowed_mime_types TEXT[]);
CREATE TABLE storage.objects(id UUID DEFAULT gen_random_uuid(),bucket_id TEXT,name TEXT);
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
GRANT USAGE ON SCHEMA storage TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON storage.objects TO authenticated;
INSERT INTO branches VALUES ('${branchA}','A'),('${branchB}','B');
UPDATE users SET branch_id='${branchA}' WHERE id='${adminId}';
INSERT INTO users(id,full_name,role_id,branch_id) VALUES ('${parentId}','Parent',4,NULL),('${financeId}','Finance',5,'${branchA}'),('${otherId}','Other admin',2,'${branchB}');
INSERT INTO students(id,branch_id,name,full_name) VALUES (1,'${branchA}','Child A','Child A'),(2,'${branchB}','Child B','Child B');
INSERT INTO parents(id,user_id) VALUES(1,'${parentId}');
INSERT INTO student_parents VALUES(1,1);
`)
const migration=await readFile(new URL('../migrations/015_parent_payments.sql',import.meta.url),'utf8')
await db.exec(migration)
await db.exec(migration)
await db.exec(`ALTER TABLE payments ENABLE ROW LEVEL SECURITY; CREATE POLICY read_fee ON payments FOR SELECT TO authenticated USING(public.can_read_fee(id));`)
async function as(id){await db.exec(`SET ROLE authenticated; SET test.user_id = '${id}';`)}
await as(adminId)
await db.query('SELECT save_branch_payment_account($1,$2,$3,$4)',[branchA,'Bank','School','123456789'])
await assert.rejects(db.query('SELECT save_branch_payment_account($1,$2,$3,$4)',[branchB,'Bank','School','123456789']),/Only a branch/)
const invoice=(await db.query("SELECT * FROM create_fee_invoice(1,'Tuition',480,'2026-10-01')")).rows[0]
await assert.rejects(db.query("SELECT * FROM create_fee_invoice(2,'Tuition',480,'2026-10-01')"),/Student is not available/)
await assert.rejects(db.query("SELECT * FROM create_fee_invoice(1,'Tuition',-1,'2026-10-01')"),/positive amount/)
await as(parentId)
assert.equal((await db.query('SELECT * FROM payments')).rows.length,1)
await assert.rejects(db.query("SELECT * FROM create_fee_invoice(1,'Tuition',480,'2026-10-01')"),/Student is not available/)
const path=`${parentId}/${invoice.id}/receipt.pdf`
await db.query("INSERT INTO storage.objects(bucket_id,name) VALUES('payment-proofs',$1)",[path])
await assert.rejects(db.query("INSERT INTO storage.objects(bucket_id,name) VALUES('payment-proofs','fake/1/file.pdf')"),/row-level security/)
const proof=(await db.query('SELECT * FROM submit_payment_proof($1,$2,$3)',[invoice.id,path,'BANK-001'])).rows[0]
const repeat=(await db.query('SELECT * FROM submit_payment_proof($1,$2,$3)',[invoice.id,path,'BANK-001'])).rows[0]
assert.equal(proof.id,repeat.id)
await assert.rejects(db.query('SELECT * FROM review_payment_proof($1,true)',[proof.id]),/Payment is not available/)
await assert.rejects(db.exec("UPDATE payments SET status='paid'"),/permission denied/)
await as(otherId)
assert.equal((await db.query('SELECT * FROM payments')).rows.length,0)
assert.equal((await db.query('SELECT * FROM payment_proofs')).rows.length,0)
assert.equal((await db.query('SELECT * FROM storage.objects')).rows.length,0)
await assert.rejects(db.query('SELECT * FROM review_payment_proof($1,true)',[proof.id]),/Payment is not available/)
await as(financeId)
assert.equal((await db.query('SELECT * FROM storage.objects')).rows.length,1)
await assert.rejects(db.query("SELECT * FROM review_payment_proof($1,false,'')",[proof.id]),/rejection reason/)
await db.query("SELECT * FROM review_payment_proof($1,false,'Reference not found')",[proof.id])
assert.equal((await db.query('SELECT status FROM payments')).rows[0].status,'pending')
await as(parentId)
const path2=`${parentId}/${invoice.id}/receipt2.pdf`
await db.query("INSERT INTO storage.objects(bucket_id,name) VALUES('payment-proofs',$1)",[path2])
const proof2=(await db.query('SELECT * FROM submit_payment_proof($1,$2,$3)',[invoice.id,path2,'BANK-002'])).rows[0]
await as(financeId)
const approved=(await db.query('SELECT * FROM review_payment_proof($1,true)',[proof2.id])).rows[0]
assert.equal(approved.status,'approved');assert.ok(approved.receipt_no);assert.equal(approved.receipt_snapshot.amount,480)
assert.equal((await db.query('SELECT status FROM payments')).rows[0].status,'paid')
await assert.rejects(db.query('SELECT * FROM review_payment_proof($1,true)',[proof2.id]),/already been reviewed/)
await db.exec('RESET ROLE;')
const notifications=(await db.query('SELECT * FROM notifications')).rows
assert.equal(notifications.filter((n)=>n.title==='New school fee invoice'&&n.user_id===parentId).length,1)
assert.equal(notifications.filter((n)=>n.title==='Payment confirmed'&&n.user_id===parentId).length,1)
assert.ok(notifications.some((n)=>n.user_id===financeId&&n.title==='Payment proof awaiting verification'))
assert.ok(notifications.every((n)=>![otherId,superId].includes(n.user_id)))
assert.equal((await db.query("SELECT * FROM payment_proofs WHERE status='approved'")).rows.length,1)
await db.close()
console.log('PASS: invoice creation, proof privacy, parent/branch isolation, rejection/resubmission, verification, receipt idempotency and notification recipients.')
