// Isolated PostgreSQL test: node supabase/tests/parent_payments.mjs /path/to/@electric-sql/pglite/dist/index.js
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'
const { PGlite } = await import(pathToFileURL(process.argv[2]).href)
const db = new PGlite()
const superId = '10000000-0000-0000-0000-000000000001'
const adminId = '10000000-0000-0000-0000-000000000002'
await db.exec(`
CREATE ROLE anon; CREATE ROLE authenticated;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS UUID LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('test.user_id', true), '')::UUID $$;
CREATE TABLE public.branches(id UUID PRIMARY KEY, name TEXT);
CREATE TABLE public.users(id UUID PRIMARY KEY, full_name TEXT, role_id SMALLINT, branch_id UUID);
CREATE FUNCTION public.auth_user_role() RETURNS SMALLINT LANGUAGE sql SECURITY DEFINER STABLE AS $$ SELECT role_id FROM public.users WHERE id = auth.uid() $$;
CREATE FUNCTION public.auth_user_branch() RETURNS UUID LANGUAGE sql SECURITY DEFINER STABLE AS $$ SELECT branch_id FROM public.users WHERE id = auth.uid() $$;
INSERT INTO users VALUES ('${superId}', 'Superadmin', 1, NULL), ('${adminId}', 'Admin', 2, NULL);
`)
for (const name of ['students', 'branch_staff', 'classes', 'parents', 'attendances', 'payments', 'expenses', 'assignments', 'assignment_submissions', 'student_classes', 'announcements', 'subscription_plans', 'subscription_invoices']) {
  await db.exec(`CREATE TABLE public.${name}(id INTEGER PRIMARY KEY, branch_id UUID);`)
}
await db.exec(await readFile(new URL('../migrations/013_audit_logs.sql', import.meta.url), 'utf8'))

const parentId='10000000-0000-0000-0000-000000000004'
const financeId='10000000-0000-0000-0000-000000000005'
const otherId='10000000-0000-0000-0000-000000000006'
const branchA='20000000-0000-0000-0000-000000000001'
const branchB='20000000-0000-0000-0000-000000000002'
await db.exec(`
ALTER TABLE students ADD name TEXT, ADD full_name TEXT;
ALTER TABLE payments ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE payments ADD student_id INTEGER, ADD invoice_no TEXT, ADD payment_type TEXT, ADD amount NUMERIC,
 ADD due_date DATE, ADD status TEXT, ADD payment_date DATE, ADD payment_method TEXT, ADD verified_by UUID, ADD verified_at TIMESTAMPTZ;
ALTER TABLE parents ADD user_id UUID;
CREATE TABLE student_parents(student_id INTEGER,parent_id INTEGER);
ALTER TABLE users ADD status TEXT DEFAULT 'active';
CREATE TABLE notifications(id SERIAL PRIMARY KEY,user_id UUID,title TEXT,message TEXT,is_read BOOLEAN,notification_type TEXT);
CREATE SCHEMA storage;
CREATE TABLE storage.buckets(id TEXT PRIMARY KEY,name TEXT,public BOOLEAN,file_size_limit BIGINT,allowed_mime_types TEXT[]);
CREATE TABLE storage.objects(id UUID DEFAULT gen_random_uuid(),bucket_id TEXT,name TEXT);
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
GRANT USAGE ON SCHEMA storage TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON storage.objects TO authenticated;
INSERT INTO branches VALUES ('${branchA}','A'),('${branchB}','B');
UPDATE users SET branch_id='${branchA}' WHERE id='${adminId}';
INSERT INTO users(id,full_name,role_id,branch_id) VALUES ('${parentId}','Parent',4,NULL),('${financeId}','Finance',5,'${branchA}'),('${otherId}','Other admin',2,'${branchB}');
INSERT INTO students(id,branch_id,name,full_name) VALUES (1,'${branchA}','Child A','Child A'),(2,'${branchB}','Child B','Child B');
INSERT INTO parents(id,user_id) VALUES(1,'${parentId}');
INSERT INTO student_parents VALUES(1,1);
`)

await db.exec(`ALTER TABLE students ADD status TEXT DEFAULT 'active';`)
await db.exec(await readFile(new URL('../migrations/015_parent_payments.sql',import.meta.url),'utf8'))
await db.exec(await readFile(new URL('../migrations/016_recurring_billing.sql',import.meta.url),'utf8'))
async function as(id){await db.exec(`SET ROLE authenticated; SET test.user_id='${id}';`)}
async function tick(day){await db.exec("RESET ROLE; SET test.user_id='';");await db.query('SELECT run_recurring_billing($1::DATE)',[day])}
await as(financeId)
await db.query("SELECT save_recurring_fee(NULL,1,'Tuition',500,20,'2099-10-01',NULL,true)")
await assert.rejects(db.query("SELECT save_recurring_fee(NULL,2,'Tuition',500,0,'2099-10-01',NULL,true)"),/Student unavailable/)
await tick('2099-09-24')
assert.equal((await db.query('SELECT * FROM billing_batches')).rows.length,0)
await tick('2099-09-25');await tick('2099-09-25')
const b=(await db.query('SELECT * FROM billing_batches')).rows[0]
const d=(await db.query('SELECT * FROM billing_drafts')).rows[0]
assert.equal((await db.query('SELECT * FROM billing_drafts')).rows.length,1)
assert.equal(Number(d.amount),480)
assert.equal((await db.query('SELECT * FROM payments')).rows.length,0)
await as(parentId)
assert.equal((await db.query('SELECT * FROM billing_batches')).rows.length,0)
assert.equal((await db.query('SELECT * FROM billing_drafts')).rows.length,0)
await assert.rejects(db.query("SELECT run_recurring_billing('2099-09-25')"),/permission denied/)
await as(otherId)
await assert.rejects(db.query("SELECT review_billing_batch($1,false,'2099-10-05')",[b.id]),/Batch unavailable/)
await as(financeId)
await db.query("SELECT review_billing_batch($1,false,'2099-10-05')",[b.id])
await assert.rejects(db.query("SELECT review_billing_batch($1,true,'2099-10-05')",[b.id]),/administrator/)
await db.query("SELECT edit_billing_draft($1,470,false,'Sibling discount adjustment')",[d.id])
assert.equal((await db.query('SELECT status FROM billing_batches')).rows[0].status,'draft')
await db.query("SELECT review_billing_batch($1,false,'2099-10-05')",[b.id])
await as(adminId)
await db.query("SELECT review_billing_batch($1,true,'2099-10-05')",[b.id])
await tick('2099-09-26')
assert.equal((await db.query('SELECT * FROM payments')).rows.length,0)
await tick('2099-09-27');await tick('2099-09-27')
assert.equal((await db.query('SELECT * FROM payments')).rows.length,1)
assert.equal((await db.query('SELECT status FROM billing_batches')).rows[0].status,'published')
assert.equal(Number((await db.query('SELECT amount FROM payments')).rows[0].amount),470)
assert.equal((await db.query("SELECT * FROM notifications WHERE title='New school fee invoice'")).rows.length,1)
await as(adminId)
await assert.rejects(db.query('SELECT reopen_billing_batch($1)',[b.id]),/already published/)
await assert.rejects(db.query("SELECT edit_billing_draft($1,1,false,'No')",[d.id]),/not editable/)
await tick('2099-10-29')
assert.equal((await db.query('SELECT * FROM billing_batches')).rows.length,2)
assert.equal((await db.query('SELECT * FROM payments')).rows.length,1)
console.log('PASS: date schedule, catch-up, repeated jobs, draft privacy, branch isolation, review/approval separation, adjustment reset, immutable published batch and notification deduplication.')
await db.close()
