-- PAPA Kindergarten System — Homework module
-- Reuses the existing assignments table and adds a separate submission table
-- because one assignment can have one submission per student.
-- Run after 005_finance_module.sql.

-- Keep compatibility with projects where the original assignments table has
-- not yet been created. Existing tables are preserved and extended below.
CREATE TABLE IF NOT EXISTS assignments (
  id                     SERIAL PRIMARY KEY,
  assignment_description TEXT,
  class_id               INTEGER REFERENCES classes(id) ON DELETE CASCADE,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─── Extend Existing Assignments ────────────────────────────────────────────
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS id INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS assignment_description TEXT;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS class_id INTEGER REFERENCES classes(id) ON DELETE CASCADE;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS branch_id UUID REFERENCES branches(id) ON DELETE SET NULL;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS subject TEXT;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS instructions TEXT;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS assigned_date DATE;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS attachment_url TEXT;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS idx_assignments_compat_id ON assignments(id);

UPDATE assignments
SET
  title = COALESCE(title, assignment_description, 'Assignment ' || id::TEXT),
  instructions = COALESCE(instructions, assignment_description, ''),
  subject = COALESCE(subject, 'General'),
  assigned_date = COALESCE(assigned_date, created_at::DATE, CURRENT_DATE),
  due_date = COALESCE(due_date, created_at::DATE + 7, CURRENT_DATE + 7),
  status = COALESCE(status, 'published');

UPDATE assignments assignment_record
SET branch_id = class_record.branch_id
FROM classes class_record
WHERE class_record.id = assignment_record.class_id
  AND assignment_record.branch_id IS NULL;

ALTER TABLE assignments ALTER COLUMN title SET NOT NULL;
ALTER TABLE assignments ALTER COLUMN subject SET DEFAULT 'General';
ALTER TABLE assignments ALTER COLUMN subject SET NOT NULL;
ALTER TABLE assignments ALTER COLUMN instructions SET DEFAULT '';
ALTER TABLE assignments ALTER COLUMN instructions SET NOT NULL;
ALTER TABLE assignments ALTER COLUMN assigned_date SET DEFAULT CURRENT_DATE;
ALTER TABLE assignments ALTER COLUMN assigned_date SET NOT NULL;
ALTER TABLE assignments ALTER COLUMN status SET DEFAULT 'draft';
ALTER TABLE assignments ALTER COLUMN status SET NOT NULL;

-- ─── Per-student Homework Submissions ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS assignment_submissions (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  assignment_id    INTEGER NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
  student_id       INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  status           TEXT NOT NULL DEFAULT 'assigned',
  submitted_at     TIMESTAMPTZ,
  parent_note      TEXT,
  attachment_url   TEXT,
  teacher_feedback TEXT,
  score            NUMERIC(5,2),
  reviewed_by      UUID REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at      TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (assignment_id, student_id),
  CHECK (score IS NULL OR (score >= 0 AND score <= 10))
);

-- Create assigned rows for existing published assignments and active class
-- enrolments. Conflict handling makes this safe to rerun.
INSERT INTO assignment_submissions (assignment_id, student_id, status)
SELECT assignment_record.id, student_class.student_id, 'assigned'
FROM assignments assignment_record
JOIN student_classes student_class ON student_class.class_id = assignment_record.class_id
WHERE assignment_record.status = 'published'
  AND (student_class.start_date IS NULL OR student_class.start_date <= assignment_record.assigned_date)
  AND (student_class.end_date IS NULL OR student_class.end_date >= assignment_record.assigned_date)
ON CONFLICT (assignment_id, student_id) DO NOTHING;

-- ─── Indexes and Updated-at Triggers ────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_assignments_branch ON assignments(branch_id);
CREATE INDEX IF NOT EXISTS idx_assignments_class_due ON assignments(class_id, due_date DESC);
CREATE INDEX IF NOT EXISTS idx_assignments_status ON assignments(status);
CREATE INDEX IF NOT EXISTS idx_assignment_submissions_assignment ON assignment_submissions(assignment_id);
CREATE INDEX IF NOT EXISTS idx_assignment_submissions_student ON assignment_submissions(student_id);
CREATE INDEX IF NOT EXISTS idx_assignment_submissions_status ON assignment_submissions(status);

DROP TRIGGER IF EXISTS assignments_updated_at ON assignments;
CREATE TRIGGER assignments_updated_at
  BEFORE UPDATE ON assignments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS assignment_submissions_updated_at ON assignment_submissions;
CREATE TRIGGER assignment_submissions_updated_at
  BEFORE UPDATE ON assignment_submissions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── Row-Level Security: Assignments ────────────────────────────────────────
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "assignments_select_by_role" ON assignments;
DROP POLICY IF EXISTS "assignments_manage_by_staff" ON assignments;

CREATE POLICY "assignments_select_by_role" ON assignments FOR SELECT TO authenticated
  USING (
    auth_user_role() = 1
    OR (auth_user_role() IN (2, 3) AND branch_id = auth_user_branch())
    OR (
      auth_user_role() = 4
      AND status = 'published'
      AND EXISTS (
        SELECT 1
        FROM student_classes student_class
        JOIN student_parents student_parent ON student_parent.student_id = student_class.student_id
        JOIN parents parent_record ON parent_record.id = student_parent.parent_id
        WHERE student_class.class_id = assignments.class_id
          AND parent_record.user_id = auth.uid()
      )
    )
  );

CREATE POLICY "assignments_manage_by_staff" ON assignments FOR ALL TO authenticated
  USING (
    auth_user_role() IN (1, 2, 3)
    AND (auth_user_role() = 1 OR branch_id = auth_user_branch())
  )
  WITH CHECK (
    auth_user_role() IN (1, 2, 3)
    AND (auth_user_role() = 1 OR branch_id = auth_user_branch())
  );

-- ─── Row-Level Security: Submissions ────────────────────────────────────────
ALTER TABLE assignment_submissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "submissions_select_by_role" ON assignment_submissions;
DROP POLICY IF EXISTS "submissions_insert_by_role" ON assignment_submissions;
DROP POLICY IF EXISTS "submissions_update_by_role" ON assignment_submissions;

CREATE POLICY "submissions_select_by_role" ON assignment_submissions FOR SELECT TO authenticated
  USING (
    auth_user_role() = 1
    OR EXISTS (
      SELECT 1 FROM assignments assignment_record
      WHERE assignment_record.id = assignment_submissions.assignment_id
        AND auth_user_role() IN (2, 3)
        AND assignment_record.branch_id = auth_user_branch()
    )
    OR EXISTS (
      SELECT 1
      FROM student_parents student_parent
      JOIN parents parent_record ON parent_record.id = student_parent.parent_id
      WHERE student_parent.student_id = assignment_submissions.student_id
        AND auth_user_role() = 4
        AND parent_record.user_id = auth.uid()
    )
  );

CREATE POLICY "submissions_insert_by_role" ON assignment_submissions FOR INSERT TO authenticated
  WITH CHECK (
    auth_user_role() = 1
    OR EXISTS (
      SELECT 1 FROM assignments assignment_record
      WHERE assignment_record.id = assignment_submissions.assignment_id
        AND auth_user_role() IN (2, 3)
        AND assignment_record.branch_id = auth_user_branch()
    )
    OR (
      auth_user_role() = 4
      AND status = 'submitted'
      AND EXISTS (
        SELECT 1
        FROM student_parents student_parent
        JOIN parents parent_record ON parent_record.id = student_parent.parent_id
        WHERE student_parent.student_id = assignment_submissions.student_id
          AND parent_record.user_id = auth.uid()
      )
      AND EXISTS (
        SELECT 1
        FROM assignments assignment_record
        JOIN student_classes student_class
          ON student_class.class_id = assignment_record.class_id
        WHERE assignment_record.id = assignment_submissions.assignment_id
          AND student_class.student_id = assignment_submissions.student_id
          AND assignment_record.status = 'published'
      )
    )
  );

CREATE POLICY "submissions_update_by_role" ON assignment_submissions FOR UPDATE TO authenticated
  USING (
    auth_user_role() = 1
    OR EXISTS (
      SELECT 1 FROM assignments assignment_record
      WHERE assignment_record.id = assignment_submissions.assignment_id
        AND auth_user_role() IN (2, 3)
        AND assignment_record.branch_id = auth_user_branch()
    )
    OR EXISTS (
      SELECT 1
      FROM student_parents student_parent
      JOIN parents parent_record ON parent_record.id = student_parent.parent_id
      WHERE student_parent.student_id = assignment_submissions.student_id
        AND auth_user_role() = 4
        AND parent_record.user_id = auth.uid()
        AND assignment_submissions.status IN ('assigned', 'submitted', 'late')
    )
  )
  WITH CHECK (
    auth_user_role() = 1
    OR EXISTS (
      SELECT 1 FROM assignments assignment_record
      WHERE assignment_record.id = assignment_submissions.assignment_id
        AND auth_user_role() IN (2, 3)
        AND assignment_record.branch_id = auth_user_branch()
    )
    OR (
      auth_user_role() = 4
      AND status = 'submitted'
      AND EXISTS (
        SELECT 1
        FROM student_parents student_parent
        JOIN parents parent_record ON parent_record.id = student_parent.parent_id
        WHERE student_parent.student_id = assignment_submissions.student_id
          AND parent_record.user_id = auth.uid()
      )
      AND EXISTS (
        SELECT 1
        FROM assignments assignment_record
        JOIN student_classes student_class
          ON student_class.class_id = assignment_record.class_id
        WHERE assignment_record.id = assignment_submissions.assignment_id
          AND student_class.student_id = assignment_submissions.student_id
          AND assignment_record.status = 'published'
      )
    )
  );
